---
title: "Homework 1"
author: "E. Kelley"
date: "9/1/2022"
output: pdf_document
---
```{r global_options, include = FALSE}
knitr::opts_chunk$set(echo=TRUE, include = TRUE, warning=FALSE, message=FALSE)
```

```{r}
suppressPackageStartupMessages(library(tidyverse))
```


## Exercise 1
```{r}
getwd()
load("compstats1.RData")
as.data.frame(ages) %>%
  mutate(ages_fac = as_factor(case_when(
    ages < 18 ~ "Minor",
    ages >= 18 ~ "Adult"
  ))) %>%
  pull(ages_fac) -> ages_fac

ages_fac
# added this later because I wanted to try it in baseR
mlab <- which(ages<18)
alab <- which(ages >=18)
new_vec <- seq_along(ages)
new_vec[mlab] <- "minor"
new_vec[alab] <- "adult"
new_vec <- as.factor(new_vec)
relevel(new_vec, ref = "minor")

```

## Exercise 2
```{r}
data(ChickWeight)
?help(ChickWeight)
CW_10_20 <- ChickWeight %>%
  filter(Time == 10 | Time==20) %>%
  group_by(Diet,Time) %>%
  mutate(wt.mean_diet_time = round(mean(weight, na.rm=T), digits=2),
         wt.sd_diet_time = round(sd(weight, na.rm=T), digits=2)) %>%
  arrange(Diet, Time) %>%
  dplyr::select(Time, Diet, wt.mean_diet_time, wt.sd_diet_time) %>%
  distinct(., .keep_all = T) 

knitr::kable(CW_10_20, col.names = c("Time", "Diet", "Mean", "Standard Deviation"))
```

## Exercise 3
```{r}
Survey <- read.csv("https://www.lock5stat.com/datasets3e/StudentSurvey.csv",
                   na.strings=c(""," ")) %>%
   mutate(Year = factor(Year, levels=c("FirstYear","Sophomore","Junior","Senior"))) %>%
   mutate(Sex = factor(Sex))

Survey_sum <- Survey %>%
  dplyr::select(Sex, Year) %>%
  filter(!(is.na(Year))) %>%
  group_by(Sex,Year) %>%
  summarize(Sex_by_Year = n()) %>%
  spread(., Sex, Sex_by_Year) %>%
  rename(Female = `F`, Male = `M`)
  
knitr::kable(Survey_sum)

# You could also just use table and do it in one line +1 for base R haha
knitr::kable(table(Survey$Year, Survey$Sex))
```

## Exercise 4
```{r}
library(MASS)
library(dplyr)
birthwt <- birthwt %>%
  mutate(
    race = factor(race, labels = c("White", "Black", "Other")),
    smoke = factor(smoke, labels = c("No Smoke", "Smoke"))
  )

p1 <- ggplot(birthwt, aes(bwt)) +
  geom_histogram()
p1 + facet_grid(~smoke)
p1 + facet_grid(smoke ~ race)
p2 <- ggplot(birthwt, aes(bwt, ..density..)) +
  geom_histogram(fill = "cornsilk", color = "grey60") +
  geom_density() +
  facet_grid(~smoke)
p3 <- p2 +
  ggtitle("geom_histogram first")

p4 <- ggplot(birthwt, aes(bwt, ..density..)) +
  geom_density() +
  geom_histogram(fill = "cornsilk", color = "grey60") +
  facet_grid(~smoke)

p5 <- p4 +
  ggtitle("geom_density first")
library(patchwork)
```

I prefer the geom_density as the top layer.  
```{r}
p3 / p5
```

